[package]
name = "jankycraft"
version = "0.1.0"
edition = "2021"

[lib]
name = "engine"
path = "Engine/lib.rs"

[[bin]]
name = "jankycraft"
path = "Game/main.rs"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
wgpu = "22.1.0"
winit = "0.29.15"
