name: CD

on:
  push:
    tags:
      - 'v*.*.*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies (Linux)
        run: sudo apt-get install -y clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
        if: runner.os == 'Linux'

      - name: Build project
        run: cargo build --release

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Archive release
        uses: thedoctor0/zip-release@0.7.6
        with:
            type: 'tar'
            filename: 'jankycraft-${{ runner.arch }}-${{ runner.os }}.tar.gz'
            directory: 'artifacts'
            path: 'target/release/jankycraft'
        if: runner.os != 'Windows'

      - name: Archive release (Windows)
        uses: thedoctor0/zip-release@0.7.6
        with:
            type: 'zip'
            filename: 'jankycraft-${{ runner.arch }}-${{ runner.os }}.zip'
            directory: 'artifacts'
            path: 'target/release/jankycraft.exe'
        if: runner.os == 'Windows'

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: artifacts/**
