name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt

    - name: Run tests
      run: cargo test --all-features

  formatting:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt

    - name: Check formatting
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt

    - name: Run clippy
      run: cargo clippy -- -D warnings